name: Update pip index
on:
  release:
    types: [published] # e
  workflow_dispatch:
  push:
    branches:
      - gh-pages  # ← triggers when you push to gh-pages

permissions:
  contents: write # write contents

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Regenerate index
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 generate_index.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add whl/ .nojekyll
          git diff --staged --quiet && echo "Nothing to commit" || git commit -m "Update pip index for ${{ github.ref_name }}"
          git push origin HEAD:gh-pages
